### ISSUE TITLE
Question: using addEventListener instead of Events?

### ISSUE THREAD

**Issue by threeid** [localvoid/ivi#14]
Hi localvoid,

Is there any downside of using addEventListener instead of Events
that i need to know? 
Because I want to use [htm](https://github.com/developit/htm) with ivi and Web components.

Thanks,
threeid

**Comment by localvoid** [comment]
Hi,

> Is there any downside of using addEventListener instead of Events that i need to know?

`Events()` provides a composable and extensible solution for events. React team recently started working on something similar (React flare).

> Because I want to use htm with ivi and Web components.

I am not sure that ivi would be a good solution if you are planning to use `htm` and web components:

- `htm` will have the same issues as jsx https://github.com/localvoid/ivi/issues/13
- [ivi doesn't support creating custom elements (Web Components)](https://github.com/localvoid/ivi#custom-elements-web-components)

**Comment by threeid** [comment]
Thank you for your reply.
