### ISSUE TITLE
HTML syntax in tagged tpl literals?

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#43]
looking at your new React / ivi examples (which are great!), i'm wondering how straightfoward it would be to make a template compiler with a more traditional HTML syntax rather than one with significant indentation and unorthodox DSL. it should make no difference in output once compiled and you can potentially leverage existing tagged template highlighters for IDEs e.g. https://github.com/mjbvz/vscode-lit-html. imo it would also be more natural to grok the templates (e.g. by designers) and a lot less cognitive load if all that needed to be learned were ivi-specific additions.

what ivi template concepts do you consider to be fundamentally non-representable in some theoretical ivi-html superset?

**Comment by leeoniya** [comment]
also, i did find https://github.com/localvoid/ivi#multiple-root-nodes to  be kind of awkward. can a babel template compiler take care of detecting these root fragment cases and just transform them mechanically as shown in the docs?

**Comment by localvoid** [comment]
> what ivi template concepts do you consider to be fundamentally non-representable in some theoretical ivi-html superset?

It is possible, and I think that it would be a good idea to switch to html-like language instead of this one. Initially I thought that this template language will be more concise, but when I've started to use it, I've changed my mind :) I'll implement html-like template language in a day or two.

> also, i did find https://github.com/localvoid/ivi#multiple-root-nodes to be kind of awkward. can a babel template compiler take care of detecting these root fragment cases and just transform them mechanically as shown in the docs?

I think it is possible even with runtime compiler, I'll try to implement it.

**Comment by localvoid** [comment]
HTML-like language will need to have some special syntax for this types of properties: 

- [`div .name=${expr}`](#properties) - Property `element[name] = expr`.
- [`div *name=${expr}`](#properties) - Property `element[name] = expr`, diffs against a DOM value.
- [`div ~name=${expr}`](#styles) - Style `element.style.setProperty(name, expr)`
- [`div @name=${expr}`](#events) - Event `element.addEventListener(name, expr)`
- [`div =${expr}`](#text-content) - Text Content `element.textContent = expr`
- [`div $${directive}`](#directives) - Directive `directive(element)`

`lit-html` also using special syntax for properties and events.

And I want to have an option to disable template cloning. I thought about using different tagged functions like `htm` and `htmClone`, or maybe using a special comment like `/**@\_\_DISABLE_CLONE__*/. Pretty much every option that I can think of is bad :)

Also, I want to remove spaces from templates after compilation. In react, it is automatically removed and they are using expressions to add spaces:

```jsx
<div>
  <span></span>
  {" "}
  <span></span>
</div>
```

In html-like templates they are often collapsed to one whitespace, and people are writing code like this:

```html
<div>
  <span></span
  ><span></span
></div>
```

Right now I am thinking about using tabs as non-collapsible whitespace between elements.

```html
<div>
  <span></span>
  \t
  <span></span>
</div>
```

**Comment by leeoniya** [comment]
> Right now I am thinking about using tabs as non-collapsible whitespace between elements.

i have trim trailing whitespace on save enabled in my editors, so that will break like markdown double trailing space for newlines (https://github.com/microsoft/vscode/issues/1679).

**Comment by leeoniya** [comment]
ultimately, i think it's more important for me personally to have syntax coloring in the template string than to have it look like HTML (this has always been my gripe with template string based frameworks), so making some kind of grammar (lezer, tree-sitter, textmate, etc) / vscode plugin for the existing DSL that tokenizes stuff with the same AST as an html parser would, would go a long way.

**Comment by localvoid** [comment]
Almost finished separating complex template compilation from template parsing, so it will be way much easier to create different template languages. Parser for the current template language is ~300 loc.

I am thinking about completely removing everything that is related to templates from the core package and make it easier to add different template parsers as an option to babel/rollup plugins (with two default parsers: html-like language and the current language).

**Comment by localvoid** [comment]
Added support for multiple root nodes in templates. Internally it just converts into an array of template nodes and it works with any node type: element, text and expressions.

**Comment by leeoniya** [comment]
looking great so far :tada: 

this is in Stage 2, btw: https://github.com/tc39/proposal-string-dedent

what's the best way to test `master` before official npm releases?

**Comment by localvoid** [comment]
Got an idea how to deal with whitespaces. By default, it should be optimized for the most common use cases with some basic rules:

1. When there is a newline character that separates different nodes, all whitespaces will be removed.

```htm
<div>
  <a></a>
  text
  <b></b>
</div>
```

```htm
<div><a></a>text<b></b></div>
```

2. When there are multiple nodes on the same line, whitespaces will be collapsed into one space character.

```htm
<div>  <a></a>  <b></b>  </div>
<div>  <a></a>  text  <b></b>  </div>
```
```htm
<div> <a></a> <b></b> </div>
<div> <a></a> text <b></b> </div>
```

3. Multiline text node will be separated with one space character.

```htm
<div>
  multi
  line
</div>
```
```htm
<div>multi line</div>
```

4. Vertical tab character as an escape hatch to add an extra space `\v`. It even looks like an arrow that points that there should be a space character :)

```htm
<div>
  <b>10</b>
  \vitems left
</div>
```

or with some extra spaces (they will be collapsed into one space):

```htm
<div>
  <b>10</b>
  \v items left
</div>
```

```htm
<div><b>10</b> items left</div>
```

> what's the best way to test master before official npm releases?

I'll start publishing 3.0-beta.N versions today.

**Comment by leeoniya** [comment]
can `@event=${onEvent}` just be a special addEventListener case of attribute or property syntax with "on" prefix? like `onclick=${onClick}`? 🤔 

or did you want the ability to set those attrs or properties explicitly? or to leave room for adding synthetic/delegated event system to the `@` prefixed variants?

**Comment by localvoid** [comment]
lit-html also using [@event](https://lit.dev/docs/v1/lit-html/writing-templates/#add-event-listeners) to add event listeners. Maybe there are some edge cases with web components/custom events. It just removes any ambiguity.

**Comment by leeoniya** [comment]
👍
