### ISSUE TITLE
missing support for static style props

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#47]
![image](https://user-images.githubusercontent.com/43234/227817619-78045720-22ad-4d05-8f30-acdf4649cb48.png)

**Comment by localvoid** [comment]
I'll implement it today.

Also, I would like to add an optimization with Typed API for styles that would require some additional syntax. Maybe something like `~padding-top.px={paddingTop}`. Internally it will reuse the same typed object. It is going to reduce memory allocations when working with styles and makes diffing style values a little bit faster.
