### ISSUE TITLE
Add utility function for dispatching Custom Events

### ISSUE THREAD

**Issue by localvoid** [localvoid/ivi#48]
One of the most common use cases for contexts in React is dispatching events, and since ivi doesn't support contexts (yet), the best way to implement event dispatching is to just use native DOM API with Custom Events. Even if ivi supported contexts, I think that for this type of use cases, Custom Events are better because it will work in situations when there is a complex parent-child chain like `[ivi component] -> [custom-element] -> [ivi-component]`

Right now, custom events can be dispatched manually by finding the closest DOM node in a component with an utility function `findDOMNode(component)`, but it would be better to provide some utility function like:

```ts
const dispatchEvent = <T>(c: Component, eventName: string, detail?: T, options?: DispatchOptions) => boolean;
```

But there is one caveat is that it won't work when component doesn't render any DOM nodes. I don't think that it will be a problem in practice, since even when component is loading something asynchronously, it will render some DOM node with a loading indicator.

**Comment by leeoniya** [comment]
for contexts i was thinking to just use a stateful wrapper component that exposes some prop like `c.ctx`, then just make a vdom ascender util like `getCtx(c, filterFn)` or `findVNode(c, filterFn).ctx` or `closestVNode`.

domvm has vnode.pull() for this.

https://domvm.github.io/domvm/demos/playground/#context

for in-vdom events, dispatch as you suggest is good. domvm has vm.emit() for this.

**Comment by localvoid** [comment]
The main issue with context is to choose a strategy for invalidating dependencies when context value is changed. I think that triggering force update in context subtree will be good enough, and if somebody wants a more granular control for updates, it will be possible to build a pub/sub solution on top of that.

**Comment by leeoniya** [comment]
> I think that triggering force update in context subtree will be good enough,

i think this will be more than fast enough in pretty much all cases given ivi's efficiency. and if there are perf issues with some specific case (mousemove context invalidation), then simply prop-drill like the good old days, or throttle/debounce.

**Comment by leeoniya** [comment]
does/will ivi ever support components that are mounted but have no DOM representation? some kind of "suspended" mode that retains state in the vtree? or is most of this expected to be handled by css `display: none`?

i see that https://github.com/localvoid/ivi#eventdispatcher is an emit system that relies on the DOM heiratchy rather than the vtree, so it makes things like emitted events that traverse portals impossible. not sure what direction you want to take in the future, but feels like using the vdom for another emit system might be useful, without having to simulate all the typical bubbling/propagation/cancellations stuff you'd normally have to deal with if doing actual synthetic events.

**Comment by localvoid** [comment]
> does/will ivi ever support components that are mounted but have no DOM representation?

Components can render any node type: `null`, templates or other components.

Or you've meant something like keep-alive? Keep-alive is definitely outside of the scope for this library, too many edge cases to deal with.

Something like React suspense is also outside of the scope.

> i see that https://github.com/localvoid/ivi#eventdispatcher is an emit system that relies on the DOM heiratchy rather than the vtree, so it makes things like emitted events that traverse portals impossible

I just want to keep it simple.

> not sure what direction you want to take in the future

It is almost finished, don't want to add any major features in the future.

> but feels like using the vdom for another emit system might be useful, without having to simulate all the typical bubbling/propagation/cancellations stuff you'd normally have to deal with if doing actual synthetic events.

context + dispatch functions.
