### ISSUE TITLE
better type inference for component instance props generic?

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#55]
@localvoid 

there's enough info here to turn `any` into `ExampleProps`?

![image](https://github.com/localvoid/ivi/assets/43234/3fe05482-24a5-4850-87be-80b02c0df107)

this one feels trickier. TS might not have the necessary reflection:

![image](https://github.com/localvoid/ivi/assets/43234/b67a09a1-1972-4349-8822-bb188077dff6)

(also, this is taken from the useEffect `@example`, which seems outdated / broken):

https://github.com/localvoid/ivi/blob/164d64cabe80d33ce4eb0907a5373f91138b5648/packages/ivi/src/client/core.ts#L1593-L1605

**Comment by localvoid** [comment]
Thanks, fixed https://github.com/localvoid/ivi/commit/1eccb41178bc59f6ba04af9be2659b3990c18e92
