### ISSUE TITLE
Is 2.7kb claim still correct?

### ISSUE THREAD

**Issue by canadaduane** [localvoid/ivi#56]
I'm exploring this great little library and I'm curious if the 2.7kb claim on the readme is still correct. When I include ivi and the @ivi/html libs, I see about 13kb of library data imported (brotli compressed):

![image](https://github.com/localvoid/ivi/assets/129/7367808b-2d3c-4d0b-b07d-52a371aee8f7)

This is from https://cdn.jsdelivr.net/npm/@ivi/htm/+esm

**Comment by localvoid** [comment]
Yes, it is the size when template precompilation is enabled (Vite, Rollup or babel plugins).

`@ivi/htm` package and many other modules will be eliminated from the final bundle when templates are precompiled.

Originally, I thought about maintaining two different modules for template compilation at runtime: one that is optimized for size and performance and another one for development. But in the end I've decided to keep it simple, maintain codebase for runtime compiler that is easy to read/update and optimize everything for template precompilation.
