### ISSUE TITLE
possible to return previous result from component's render() to signal noop?

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#57]
hey @localvoid :wave: 

i'm playing around with a silly component that can fetch its own data in a useEffect that depends on a seed from the parent which can be incremented by a button in the parent to manually refetch/redraw just this table. (never mind if it's a good idea...i was asked by a friend coming  from jQuery :P)

when this seed is incremented, we know that we will see an update sometime later after a re-fetch, but during _this_ cycle i would like to reuse the previous render result and noop from within the render function. i cannot use the `areEqual` in the component definition because the seed changes and the useEffect has to be scheduled, which means that render() needs to run.

something like `return IVI_NOOP;` or `return getPrevRender(c)`  or `return usePrevious(c)`?

any advice? thanks!

```ts
import { component, useState, useEffect, getProps, strictEq } from "ivi";
import { htm as html } from "@ivi/htm";
import { fakeFetch } from './data.js';

interface TableProps {
  cap: string;
  url: string;
  seed: number;
}

interface TableData {
  fields: string[];
  data: string[][];
}

export const Table = component<TableProps>((c) => {
  let [data, setData] = useState<TableData | null>(c, null);

  const update = useEffect(c, (seed: number) => {
    let { url } = getProps(c);

    fakeFetch(url)
      .then(r => r.json())
      .then(setData);
  }, strictEq);

  return (p) => {
    update(p.seed);

    let d = data();

    if (d == null) {
      return null;
    }

    return html`
      <div>
        <h3>${p.cap}</h3>
        <table>
          <thead>
            <tr>
              ${d.fields.map(fld => html`
                <th>${fld}</th>
              `)}
            </tr>
          </thead>
          <tbody>
            ${d.data.map(row => html`
              <tr>
                ${row.map(col => html`
                  <td>
                    ${col}
                  </td>
                `)}
              </tr>
            `)}
          </tbody>
        </table>
      </div>
    `;
  };
});
```

**Comment by localvoid** [comment]
When render function returns the same node, it should short-circuit updates (similar to React) 
https://github.com/localvoid/ivi/blob/43cdf6f747dc782883ca73bdb5b4e21fa9c27655/packages/ivi/src/client/core.ts#L602-L605

```ts
export const Table = component<TableProps>((c) => {
  let c;
  return (p) => c === void 0 ? (c = html`<div/>`) : c;
});
```

**Comment by leeoniya** [comment]
ah, nice. :+1:
