### ISSUE TITLE
useState getter as a setter?

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#58]
hey @localvoid 

it would be nice if the useState getter can also be a setter:

now:

```ts
let [seed1, setSeed1] = useState<number>(c, 0);
setSeed1(8);
```

maybe:
```ts
let [seed1] = useState<number>(c, 0);
seed1(8);
```

this lets you have just a single "thing" to work with for each state value. any reason this is a bad idea except being unable to set the state to `undefined` (i usually use `null`)?

coming back to the example in https://github.com/localvoid/ivi/issues/57, the parent looks like this:

```ts
import { component, createRoot, update, useState } from "ivi";
import { htm as html } from "@ivi/htm";
import { Table } from "./Table.js";

const App = component((c) => {
  let [seed1, setSeed1] = useState<number>(c, 0);
  let [seed2, setSeed2] = useState<number>(c, 0);

  return () => html`
    ${Table({url: 'f1', cap: 'Routes', seed: seed1() })}
    ${Table({url: 'f2', cap: 'Operators', seed: seed2() })}
    <button @click=${() => setSeed1(seed1() + 1)}>Update Table 1</button>
    <button @click=${() => setSeed2(seed2() + 1)}>Update Table 2</button>
  `;
});

update(createRoot(document.body), App());
```

but it could look like this:

```ts
const App = component((c) => {
  let [seed1] = useState<number>(c, 0);
  let [seed2] = useState<number>(c, 0);

  let incr = seed => seed(seed() + 1);

  return () => html`
    ${Table({url: 'f1', cap: 'Routes', seed: seed1() })}
    ${Table({url: 'f2', cap: 'Operators', seed: seed2() })}
    <button @click=${() => incr(seed1)}>Update Table 1</button>
    <button @click=${() => incr(seed2)}>Update Table 2</button>
  `;
});
```

**Comment by leeoniya** [comment]
i guess i can always write my own in userland in 5 LOC :)

https://github.com/localvoid/ivi/blob/43cdf6f747dc782883ca73bdb5b4e21fa9c27655/packages/ivi/src/client/state.ts#L59

made this one which has a better feel to it, since ivi returns a getter/fn, the separate setter isnt strictly needed as it is in React-land.

```ts
import { Component, invalidate } from "ivi";

export const useState2 =
  <S>(component: Component, state: S) =>
  (next?: S) => {
    if (next !== void 0 && next !== state) {
      state = next;
      invalidate(component);
    }
    return state;
  };
```

**Comment by localvoid** [comment]
> any reason this is a bad idea

I've used `[getter, setter] = fn()` API because a lot of people are already familiar with React `useState()` function. `useState()` is just an optional utility function and it is perfectly fine to create different high-level APIs for managing local state like you've done with `useState2()`.
