### ISSUE TITLE
DOC: composition link is broken

### ISSUE THREAD

**Issue by brucou** [localvoid/ivi#6]
I am referrign to this link : https://codesandbox.io/s/k9m8wlqky3

**Comment by localvoid** [comment]
Checked right now and it seems to be working fine, maybe there were some issues with the codesandbox. Or you mean that example at this URL doesn't work? Checked in Chrome/Safari/Firefox and it seems to be working as expected.

**Comment by brucou** [comment]
alright, it is working now. So strange. Thank you in any case. On another note, I will be writing a demo app in ivi, That is the typical query app, where the user types stuff in an input field and every key typed fires a request to a database, and there are results displayed. The user can also pick one result and see some details. So not a big big app, but bigger than those you have so far as examples (which are great because small apps exemplify your point in an easier way). So could be interesting to add to the README when it is done.
