### ISSUE TITLE
@ivi/htm compiler removes whitespace between inline elements

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#61]
@localvoid 

```htm
<td><img src=${e.actor_img}> ${e.actor}</td>
```

the space after the `img` element is getting removed.

**Comment by leeoniya** [comment]
should it be v3.0.3? :thinking: 

https://github.com/localvoid/ivi/releases/tag/htm%2F3.0.3

![image](https://github.com/localvoid/ivi/assets/43234/9a2cc894-0ff5-4680-a2f2-17ef196ab8f7)

**Comment by leeoniya** [comment]
~~yeah, 3.0.2 does not work :(~~

no, never mind. it works. still don't understand why the version numbers are off.

**Comment by localvoid** [comment]
Sorry, I've made a typo when I've made a github release. It should be 3.0.2.
