### ISSUE TITLE
useEffect cannot accept an async function

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#62]
@localvoid 

i have to pass it a regular function containing an async iife wrapper if i want to use `await` loops inside.

(probably same applies to IdleEffect and LayoutEffect)

**Comment by localvoid** [comment]
`useEffect()` hook in React also doesn't work with async functions. https://devtrium.com/posts/async-functions-useeffect

**Comment by leeoniya** [comment]
ok, that explanation makes sense :+1:
