### ISSUE TITLE
@ivi/htm: whitespace between dynamic bits disappears

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ivi#65]
@localvoid 

```js
`
${table.schema.cols.map((c, i) => html`
  <th @click=${() => onClickCol(i)}>
    ${c.name}
    ${sortDir[i] || ''}
    ${sortPos[i] || ''}
  </th>
`)}
`
```

creates 3 adjacent text nodes with no white space between:

```html
<th>genre11</th>
```

![image](https://github.com/localvoid/ivi/assets/43234/b54cbf94-55bb-4411-b74e-4a61098bdc62)

also behaves a bit differently when in single line:

```js
`
${table.schema.cols.map((c, i) => html`
  <th @click=${() => onClickCol(i)}>${c.name} ${sortDir[i] || ''} ${sortPos[i] || ''}</th>
`)}
`
```

```html
<th>title <!---->11</th>
```

![image](https://github.com/localvoid/ivi/assets/43234/bf8325e5-6f05-4b54-bd90-a5f41770716d)

**Comment by leeoniya** [comment]
inserting `&nbsp;` in between doesn't quite work, either:

```js
`
${table.schema.cols.map((c, i) => html`
  <th @click=${() => onClickCol(i)}>
    ${c.name}
    &nbsp;
    ${sortDir[i] || ''}
    &nbsp;
    ${sortPos[i] || ''}
  </th>
`)}
`
```

```html
<th>genre&nbsp;<!---->11</th>
```

![image](https://github.com/localvoid/ivi/assets/43234/49ecf8d9-cbf3-47aa-910c-800d532a7752)

**Comment by leeoniya** [comment]
@localvoid any chance of getting this patched?

**Comment by localvoid** [comment]
I'll try to figure out what causing this issue and fix it next week, but I am not sure that I'll have a lot of time to work on this project.

**Comment by leeoniya** [comment]
> I'll try to figure out what causing this issue and fix it next week

thanks :)

> but I am not sure that I'll have a lot of time to work on this project.

that's too bad :(, but i get it.

**Comment by leeoniya** [comment]
@localvoid ping :pray:

**Comment by localvoid** [comment]
Released a new version that should fix the bug with a comment node.

The first example with newlines works as expected, by default all whitespaces around newlines between elements and expressions are removed (https://github.com/localvoid/ivi/blob/master/packages/@ivi/htm/README.md#whitespaces). There is a workaround with vertical tab `\v` for such use cases:

```js
`
${table.schema.cols.map((c, i) => html`
  <th @click=${() => onClickCol(i)}>
    ${c.name}
    \v${sortDir[i] || ''}
    \v${sortPos[i] || ''}
  </th>
`)}
`
```

**Comment by leeoniya** [comment]
thanks!
