### ISSUE TITLE
ivi 4.0

### ISSUE THREAD

**Issue by localvoid** [localvoid/ivi#67]
Overall goal is to reduce code complexity and focus on use cases in which ivi library will have an advantage over other solutions.

## Remove SSR / hydration

Current hydration algorithm assumes that DOM tree structure is identical to an HTML string generated by an SSR algorithm, but in practice there are edge cases (browser extensions, etc...) that break this assumption. Removing SSR/hydration should significantly reduce the complexity of the code base.

- Remove Astro plugin.
- Optimize OpCodes. Without hydration, `StateOpCode.PrevExpr` is unnecessary.

## Switch from `babel` to `typescript`

- Since most projects are already using typescript, switching to typescript library as a js parser library should reduce the number of dependencies (reduce node_modules bloat).
- TypeScript library is actively maintained.

## Hoist expressions #60 

- It should be safe to automatically hoist event listener functions.
- Add `/* preventHoist */` annotation to disable auto hoisting. In some use cases it can be beneficial to avoid hoisting to slightly reduce memory usage.
- It should find the outermost hoisting scope that is possible for an expression. 

## Remove `@ivi/tpl` syntax

- Remove `@ivi/tpl` and `@ivi/htm` packages.
- Move `htm` and `svg` functions from `@ivi/htm` package to `ivi` package.

**Comment by leeoniya** [comment]
nice!

@localvoid any thoughts on something like ivi-router and/or error-boundary?

it would be great to have a lightweight routing solution either in core or as a docs example of how to integrate a pluggable router into a non-trivial app. apps with any kind of appreciable complexity need to have functional bookmarking and nav history, nested routes (and often route-based code splitting). i feel like it's a significant missing piece in ivi. i'm not sure how feasible it is to keep this insulated without dictating how route-based state/fetching is handled, though a state-management solution based on something like https://github.com/unadlib/mutative could be interesting.

**Comment by localvoid** [comment]
I want to reduce the scope of the library, so it would be way much easier to maintain.

Personally, I wouldn't use ivi for complex web applications. For the past couple of years I've explored the idea of building UI apps by using [DBSP](https://sigmodrecord.org/publications/sigmodRecord/2403/pdfs/20_dbsp-budiu.pdf) for an application state `Model` that incrementally updates `ViewModel` projection (signals) that it is projected onto `View` (DOM). DBSP-based local relational db for an app state pretty much solved all issues that I had with "signals"-based UI libraries, except for some use cases when it is significantly faster to perform diffing, so I want to keep ivi library alive to handle such use cases.

I think that soon we are going to see some publicly available solutions that use DBSP ideas. e.g.

 - https://zero.rocicorp.dev/
 - https://hyperfiddle-docs.notion.site/Talk-Electric-Clojure-v3-Differential-Dataflow-for-UI-Getz-2024-2e611cebd73f45dc8cc97c499b3aa8b8

**Comment by leeoniya** [comment]
understood. i will see what can be done outside the core.

btw, is manually hoisting _Button necessary here?

https://github.com/localvoid/ivi?tab=readme-ov-file#stateless-components-with-areequal-hook

can't the compiler do this?

also, since you're switching to tsc instead of babel, is the textContent optimization in https://github.com/localvoid/ivi/issues/66 feasible now? 🤔

**Comment by localvoid** [comment]
> btw, is manually hoisting _Button necessary here?
> https://github.com/localvoid/ivi?tab=readme-ov-file#stateless-components-with-areequal-hook
> can't the compiler do this?

I think that it should be ok to hoist inner function in basic cases like this one `component(() => () => ...)` when it can be easily detected that inner expression doesn't have any side effects.

> also, since you're switching to tsc instead of babel, is the textContent optimization in #66 feasible now? 🤔

It is possible with `rollup` + `rollup-typescript` plugin. But I think that all modern toolchains are going to strip all types before any custom transformation plugins.

**Comment by leeoniya** [comment]
> I think that it should be ok to hoist inner function in basic cases like this one

for the example shown of adding areEqual to stateless components, this should always be true 🤔 

with such hoisting maybe the concept of stateless can be fully removed and stateless just becomes a compiler optimization.

**Comment by localvoid** [comment]
> with such hoisting maybe the concept of stateless can be fully removed and stateless just becomes a compiler optimization.

Yes, you're right. Also, it isn't just about "stateless" components, the same optimization can be applied to a stateful components like this one: https://github.com/localvoid/ivi?tab=readme-ov-file#integrating-externalimperative-libraries

**Comment by leeoniya** [comment]
tbh, i find the `findDOMNode` integration example somewhat overlapping with directives, that the docs also refer to a main use case of invoking a callback to set a dom ref. but agreed that the findDOMNode variant is more easily pure/hoistable.

**Comment by localvoid** [comment]
Added simple component render function hoisting for patterns like this `component(() => (...) => ..., ...)`. I am not sure if I want to add a lot of complexity to handle more complicated patterns into ivi transformer plugin, since it already has some ugly workarounds like getting access to a TypeChecker (for symbol resolution) when transforming isolated modules.

**Comment by leeoniya** [comment]
@localvoid have you seen any sourcemap issues in your apps?

this isnt new to v4, but i'm finding it impossible to set breakpoints in numerous places in chrome devtools. i can provide some examples if you can't repro this.

also chrome's line-level performance profile annotations dont seem to work :(

**Comment by localvoid** [comment]
Just tried to set breakpoints in TodoMVC app https://github.com/localvoid/ivi-examples/tree/master/apps/todomvc-htm and overall it seems to be working the same as when I disable ivi plugin. I think that it is impossible (not sure) to set breakpoints between template expressions the same way it is impossible to set breakpoints between expressions inside of an array.

**Comment by leeoniya** [comment]
for example, build [uTable](https://github.com/leeoniya/uTable), run [http-server](https://www.npmjs.com/package/http-server) in the repo root, and drag/drop this CSV into it:  [table0.zip](https://github.com/user-attachments/files/18031712/table0.zip).

when i try to set a breakpoint at line 241, Chrome sets a breakpoint at 215. it also plain refuses to set a breakpoint on line 184.

![image](https://github.com/user-attachments/assets/bb568eaf-efe4-45eb-8469-494f515cbdab)

here's a line-level profile of a file without sourcemaps: https://leeoniya.github.io/uPlot/demos/sine-stream.html

![image](https://github.com/user-attachments/assets/26442d51-9880-41c9-adce-0374b4901317)

**Comment by localvoid** [comment]
I am unable to set a breakpoint at line 241 even when `ivi` plugin is disabled and `terser` plugin is enabled.

**Comment by leeoniya** [comment]
hmm, maybe i should try swc and see if things improve. https://github.com/privatenumber/minification-benchmarks

**Comment by leeoniya** [comment]
yeah, [this](https://github.com/leeoniya/uTable/commit/224a618465591a46fcc06e6de4cc5027ad8efcc0) fixed it. sorry for the noise. still, line-level profile annotations only work with minification disabled, but that appears to be a common problem.
